import {useCallback,useEffect,useState} from "react";
import {z} from "zod";
import {useEditor} from "./editor-control";
import {api} from "./api";
import {useStructureActions} from "./structure-actions";
import type {Proposal} from "./structure-types";
import "./capture.css";
type Progress={revision:number;status:string;step:string;preferred_name:string;timezone:string;purpose:string;classification_name:string;description:string;examples:string;proposal_id?:string};
function SetupGuard({dirty,busy,save,close}:{dirty:boolean;busy:boolean;save:()=>Promise<unknown>;close:()=>void}){useEditor({kind:"record",mode:"edit",dirty,busy,schema:z.object({}),values:{form:"Personal setup"},patch:async()=>{throw Error("Use setup tools to save the user’s answers.");},save,close,discard:close});return null;}
export function Onboarding({compact=false,onChanged,onTalk}:{compact?:boolean;onChanged:()=>void;onTalk:()=>void}){
 const [progress,setProgress]=useState<Progress|null>(null),[draft,setDraft]=useState<Progress|null>(null),[open,setOpen]=useState(false),[dirty,setDirty]=useState(false),[proposal,setProposal]=useState<Proposal|null>(null);
 const {run,busy,error,setError}=useStructureActions();
 const load=useCallback(async()=>{const p=await api<Progress>("/onboarding");setProgress(p);setDraft(p);setDirty(false);if(p.proposal_id)setProposal(await api<Proposal>("/structure/proposals/"+p.proposal_id));else setProposal(null);},[]);
 useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
 useEffect(()=>{if(!open||dirty||busy)return;const timer=setInterval(()=>void load().catch(e=>setError(e.message)),5000);return()=>clearInterval(timer);},[open,dirty,busy,load]);
 if(!progress||!draft)return compact?null:<p role="status">{error||"Loading setup…"}</p>;
 if(compact&&!open&&["completed","skipped"].includes(progress.status))return null;
 const field=(key:keyof Progress,value:string)=>{setDraft({...draft,[key]:value});setDirty(true);setProposal(null);};
 const save=async(status="in_progress",step=draft.step)=>{const p=await run<Progress>("onboarding.save",{expected_revision:progress.revision,status,step,preferred_name:draft.preferred_name,timezone:draft.timezone,purpose:draft.purpose,classification_name:draft.classification_name,description:draft.description,examples:draft.examples});setProgress(p);setDraft(p);setDirty(false);onChanged();return p;};
 const preview=async()=>{const p=await save("in_progress","organization");const result=await run<{progress:Progress;proposal:Proposal}>("onboarding.preview",{expected_revision:p.revision});setProgress(result.progress);setDraft(result.progress);setProposal(result.proposal);};
 const complete=async()=>{if(!proposal)return;if(!proposal.applied_at){await run("structure.apply",{proposal_id:proposal.id,expected_revision:proposal.schema_revision});setProposal({...proposal,applied_at:new Date().toISOString()});}await save("completed","done");setOpen(false);onChanged();};
 return <section className="setup-panel" aria-label="Set up with Eri"><h2>{progress.status==="completed"?"Your setup":"Make Eridani yours"}</h2><p>Your Personal account has its own records. Shared workspaces show only the records and role you were invited to use.</p>
 {!open?<div className="setup-actions"><button className="btn btn-primary" onClick={()=>setOpen(true)}>{progress.status==="not_started"?"Set up with Eri":progress.status==="completed"?"Review setup":"Resume setup"}</button>{progress.status==="not_started"&&<button className="btn" disabled={busy} onClick={()=>void save("skipped").catch(()=>{})}>Skip for now</button>}</div>:<>
 <SetupGuard dirty={dirty} busy={busy} save={()=>save()} close={()=>setOpen(false)}/>
 <p>Use this short guide, or talk to Eri. Say “help me set up my account”; Eri can save these answers through chat or voice. No example tasks are created.</p><button className="btn" onClick={onTalk}>Talk to Eri</button>
 {error&&<div role="alert"><p>{error} Your answers are kept on this screen.</p><button className="btn" onClick={()=>void load().then(()=>setError(""))}>Reload saved progress</button></div>}
 <fieldset disabled={busy}><legend>What should Eri know first?</legend><label className="field">Preferred name<input aria-label="Setup name" value={draft.preferred_name} maxLength={100} onChange={e=>field("preferred_name",e.target.value)}/></label><label className="field">Time zone<input aria-label="Setup timezone" value={draft.timezone} onChange={e=>field("timezone",e.target.value)}/></label><label className="field">What do you want to track?<textarea aria-label="Setup purpose" value={draft.purpose} placeholder="Personal plans, work for clients, courses…" onChange={e=>field("purpose",e.target.value)}/></label>
 <details open={draft.step!=="profile"||!!draft.classification_name}><summary>How would you like to organize it?</summary><p>Keep the editable defaults: spaces, clients, projects, goals, tasks and notes. Or add a grouping of your own. All types, fields and relationships can be changed later in Organization → Types & fields.</p><label className="field">Optional grouping name<input aria-label="Grouping name" placeholder="Course, Client, Property…" maxLength={80} value={draft.classification_name} onChange={e=>field("classification_name",e.target.value)}/></label>{draft.classification_name&&<><label className="field">What belongs in this group?<textarea aria-label="Grouping description" minLength={20} maxLength={4500} value={draft.description} onChange={e=>field("description",e.target.value)}/></label><label className="field">Give one example and how a project relates to it<input aria-label="Grouping example" maxLength={450} value={draft.examples} onChange={e=>field("examples",e.target.value)}/></label><p className="footnote">This explanation helps Eri ask useful field questions and learn filing rules. It is separate from personal memory.</p></>}</details></fieldset>
 <div className="setup-actions"><button className="btn" disabled={busy||!draft.preferred_name.trim()} onClick={()=>void save().catch(()=>{})}>Save progress</button><button className="btn btn-primary" disabled={busy||!draft.preferred_name.trim()} onClick={()=>void preview().catch(()=>{})}>Preview my organization</button><button className="btn" disabled={busy} onClick={()=>void save("skipped").then(()=>setOpen(false)).catch(()=>{})}>Save & finish later</button></div>
 {proposal&&!dirty&&<div className="setup-example"><h3>Preview — nothing added yet</h3><p>{draft.classification_name||"Project"} → Example project → First task</p><p>Existing records are retained. Types remain editable; nothing requires a client or project.</p><details><summary>Types and descriptions</summary>{proposal.definition.types.map(t=><p key={t.id}><strong>{t.name}</strong> — {t.description}</p>)}</details><p>{proposal.impact.blocking_count} blocking issues</p><button className="btn btn-primary" disabled={busy||!!proposal.impact.blocking_count} onClick={()=>void complete().catch(()=>{})}>Confirm this setup</button></div>}
 </>}</section>;
}
