import {SearchAliases} from "./SearchAliases";
import { useCallback, useEffect, useState } from "react";
import { api } from "./api";
import { useStructureActions } from "./structure-actions";
type Rule={id:string;revision:number;status:string;origin:string;reason:string;condition:{phrase:string;type_id:string};evidence_ids:string[]};
type Review={id:string;revision:number;status:string;deferred_until:string|null;summary:{message?:string;activated?:string[]};questions:{id:string;question:string;evidence_count:number;held_out:number}[]};
type Understanding={definition_id:string;revision:number;status:string;questions:string[];understanding:{meaning?:string}};
type Prefs={routing_mode:string;routing_learning:boolean;routing_review_enabled:boolean;routing_review_day:number;routing_review_hour:number;work_windows:{days:number[];start:string;end:string}[];timezone:string};
type State={patterns:Rule[];reviews:Review[];understandings:Understanding[];preferences:Prefs;quality_gate:string};
export function RoutingReviewPanel(){
 const [state,setState]=useState<State|null>(null),[open,setOpen]=useState(false),[answer,setAnswer]=useState(""),[count,setCount]=useState(0),[more,setMore]=useState(false);const {run,busy,error,setError}=useStructureActions();
 const load=useCallback(()=>api<State>("/structure/routing/state").then(setState),[]);
 useEffect(()=>{void load().catch(e=>setError(e.message));},[load,setError]);
 const pending=Boolean(state?.reviews.some(r=>["queued","running"].includes(r.status))||state?.understandings.some(s=>s.status==="assessing"));
 useEffect(()=>{if(!pending)return;const timer=setInterval(()=>void load().catch(e=>setError(e.message)),5000);return()=>clearInterval(timer);},[pending,load,setError]);
 const action=async(tool:string,args:unknown)=>{await run(tool,args);await load();};
 if(!state)return <p role="status">{error||"Loading organization learning…"}</p>;
 const prefs=state.preferences;
 const change=(p:Record<string,unknown>)=>void action("settings.update",p).catch(()=>{});
 const review=state.reviews.find(r=>r.status==="pending"&&r.questions.length&&(!r.deferred_until||new Date(r.deferred_until)<=new Date()));const question=review?.questions[0];
 const understanding=state.understandings.find(s=>s.status==="needs_input");
 return <section className="routing-preferences"><h2>Organization learning</h2><p>Rules learn how you file work. Personal memories stay separate.</p>{error&&<p role="alert" className="error">{error}</p>}
 <div className="structure-controls"><label>New task routing<select value={prefs.routing_mode} disabled={busy} onChange={e=>change({routing_mode:e.target.value})}><option value="automatic">Apply strong matches</option><option value="suggest">Suggest only</option><option value="off">Off</option></select></label>
 <label className="check-label"><input type="checkbox" checked={prefs.routing_learning} onChange={e=>change({routing_learning:e.target.checked})}/>Learn from my organization</label>
 <label className="check-label"><input type="checkbox" checked={prefs.routing_review_enabled} onChange={e=>change({routing_review_enabled:e.target.checked})}/>Weekly review</label>
 <label>Review day<select value={prefs.routing_review_day} onChange={e=>change({routing_review_day:Number(e.target.value)})}>{["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label>
 <label>Hour ({prefs.timezone})<input type="number" min={0} max={23} defaultValue={prefs.routing_review_hour} onBlur={e=>change({routing_review_hour:Number(e.target.value)})}/></label>
 <button disabled={busy||pending||!prefs.routing_learning} onClick={()=>void action("routing.run",{}).catch(()=>{})}>Run now</button><button onClick={()=>{setOpen(!open);setCount(0);setMore(false);void load();}}>Review {state.patterns.filter(r=>r.status==="candidate").length||""}</button></div>
 {pending&&<p role="status">Eri is reviewing your organization in the background…</p>}
 <details><summary>Work hours · a hint, never a rule</summary>{prefs.work_windows.map((w,i)=><div className="schema-inline" key={i}><label>Days<select multiple value={w.days.map(String)} onChange={e=>change({work_windows:prefs.work_windows.map((x,n)=>n===i?{...x,days:Array.from(e.target.selectedOptions,o=>Number(o.value))}:x)})}>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((d,n)=><option key={d} value={n}>{d}</option>)}</select></label>{(["start","end"] as const).map(key=><label key={key}>{key}<input type="time" defaultValue={w[key]} onBlur={e=>change({work_windows:prefs.work_windows.map((x,n)=>n===i?{...x,[key]:e.target.value}:x)})}/></label>)}<button onClick={()=>change({work_windows:prefs.work_windows.filter((_,n)=>n!==i)})}>Remove</button></div>)}<button onClick={()=>change({work_windows:[...prefs.work_windows,{days:[0,1,2,3,4],start:"08:00",end:"17:00"}]})}>Add hours</button><p>End before start means an overnight shift.</p></details>
 {open&&<div className="routing-review" aria-live="polite">{count>=3&&!more?<><p>Three answered. Keep going or leave the rest for later?</p><button onClick={()=>setMore(true)}>Continue</button><button onClick={()=>setOpen(false)}>Done for now</button></>:understanding?<><h3>Help Eri understand {understanding.definition_id.split(":").at(-1)}</h3><p>{understanding.questions[0]}</p><textarea aria-label="Field clarification" value={answer} onChange={e=>setAnswer(e.target.value)}/><button disabled={busy||!answer.trim()} onClick={()=>void action("routing.understand",{definition_id:understanding.definition_id,expected_revision:understanding.revision,answer}).then(()=>{setAnswer("");setCount(count+1);}).catch(()=>{})}>Answer</button></>:question&&review?<><h3>{question.question}</h3><p>{question.evidence_count} independent examples · {question.held_out} held-out matches</p><div className="structure-controls">{[["accept","Yes, use this rule"],["dismiss","Dismiss"],["defer_today","Later today"],["defer_tomorrow","Tomorrow"],["defer_week","Next week"]].map(([value,label])=><button key={value} disabled={busy} onClick={()=>void action("routing.answer",{review_id:review.id,expected_revision:review.revision,question_id:question.id,action:value}).then(()=>setCount(count+1)).catch(()=>{})}>{label}</button>)}</div></>:<p>{state.reviews[0]?.summary.message||"No questions waiting. You can still inspect your rules below."}</p>}</div>}
 <details><summary>Rules ({state.patterns.length})</summary><p className="subtle">{state.quality_gate}</p>{state.patterns.map(r=><article className="routing-rule" key={r.id}><strong>“{r.condition.phrase}”</strong><span>{r.status} · {r.origin}</span><p>{r.reason}</p><small>{r.evidence_ids.length} examples</small><div className="structure-controls">{[[r.status==="active"?"pause":"activate",r.status==="active"?"Pause":"Confirm & enable"],["forget","Forget"]].map(([value,label])=><button key={value} disabled={busy} onClick={()=>void action("routing.change",{pattern_id:r.id,expected_revision:r.revision,action:value}).catch(()=>{})}>{label}</button>)}</div></article>)}</details>
 <SearchAliases/>
 </section>;
}
export function NotificationPreferences(){
 const [p,setP]=useState<Record<string,unknown>|null>(null);const {run,busy,error}=useStructureActions();
 useEffect(()=>{api<{preferences:Record<string,unknown>}>("/bootstrap").then(r=>setP(r.preferences)).catch(()=>{});},[]);
 const save=async(change:Record<string,unknown>)=>{const result=await run<Record<string,unknown>>("settings.update",change);setP(result);};
 if(!p)return null;
 return <section><h2>Notifications</h2>{error&&<p role="alert">{error}</p>}{[["deadline_alerts","Alert me at timed task deadlines"],["quiet_enabled","Quiet hours"],["morning_summary","Daily summary"]].map(([key,label])=><label className="check-label" key={key}><input disabled={busy} type="checkbox" checked={Boolean(p[key])} onChange={e=>void save({[key]:e.target.checked}).catch(()=>{})}/>{label}</label>)}<div className="structure-controls">{[["quiet_start","Quiet starts"],["quiet_end","Quiet ends"]].map(([key,label])=><label key={key}>{label}<input type="time" defaultValue={String(p[key])} onBlur={e=>void save({[key]:e.target.value}).catch(()=>{})}/></label>)}<label>Summary hour<input type="number" min={0} max={23} defaultValue={Number(p.morning_hour)} onBlur={e=>void save({morning_hour:Number(e.target.value)}).catch(()=>{})}/></label></div><p className="subtle">Times use {String(p.timezone)}. Only alerts explicitly marked urgent bypass quiet hours. Task priority does not. Date-only deadlines appear in your summary.</p></section>;
}
