import {useEffect,useRef,useState} from "react";
import {z} from "zod";
import {api} from "./api";
import {Dialog} from "./ux";
import {useStructureActions} from "./structure-actions";
import {useEditor} from "./editor-control";
import type {Task} from "./types";
import "./capture.css";
function CaptureGuard({busy,dirty,close}:{busy:boolean;dirty:boolean;close:()=>void}){useEditor({kind:"task",mode:"edit",dirty,busy,schema:z.object({}),values:{capture:"Quick list"},patch:async()=>{throw Error("Fill the Quick list form or use Quick capture tools.");},close,discard:close});return null;}
type List=Task&{items:Task[];done:number;total:number};
export function parseChecklist(text:string){let section="";return text.split("\n").flatMap(line=>{const value=line.trim();if(!value)return [];if(value.startsWith("# ")){section=value.slice(2).trim();return [];}return [{title:value.replace(/^[-*] (?:\[ \] )?/,""),section}];});}
export function QuickCapture({onCreated,today}:{onCreated:(task:Task)=>void;today:string}){
 const [open,setOpen]=useState(false),[title,setTitle]=useState(""),[text,setText]=useState(""),[due,setDue]=useState(""),[clock,setClock]=useState(""),[pin,setPin]=useState(false);const {run,busy,error}=useStructureActions();
 return <><button className="btn btn-soft" onClick={()=>setOpen(true)}>+ Quick list</button>{open&&<Dialog aria-label="New Quick list" className="dialog-card capture-card" onEscape={()=>{if(!busy)setOpen(false);}}><CaptureGuard busy={busy} dirty={!!(title||text)} close={()=>setOpen(false)}/><h2>One list. No setup.</h2><p>A checklist for what you’re doing now. Use # for optional section headings.</p><form onSubmit={e=>{e.preventDefault();void run<Task>("quicklist.create",{title,items:parseChecklist(text),due_date:due||null,due_time:due&&clock?clock:null,planned_date:pin?today:null}).then(task=>{setOpen(false);setTitle("");setText("");setDue("");setClock("");setPin(false);onCreated(task);}).catch(()=>{});}}>
 <label className="field">List title<input aria-label="List title" required maxLength={500} value={title} onChange={e=>setTitle(e.target.value)}/></label>
 <label className="field">Checklist<textarea aria-label="Checklist" rows={7} value={text} onChange={e=>setText(e.target.value)} placeholder={"# Hayes\nPack food\n# Moped\nGather tools"}/></label><div className="capture-options"><label className="field">Optional deadline<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label className="field">Optional time<input aria-label="Deadline time" type="time" disabled={!due} value={clock} onChange={e=>setClock(e.target.value)}/></label><label><input type="checkbox" checked={pin} onChange={e=>setPin(e.target.checked)}/> Pin to Today</label></div>
 <p className="footnote">No alerts unless you turn them on. Unfinished items stay when the deadline passes.</p>{error&&<p role="alert">{error}</p>}<button className="btn btn-primary" disabled={busy||!title.trim()||parseChecklist(text).length>100}>Create list</button><button type="button" className="btn" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button></form></Dialog>}</>;
}
export function QuickListDetail({id,onClose,onChanged,canEdit=true,today,refresh=0}:{refresh?:number;id:string;onClose:()=>void;onChanged:()=>void;canEdit?:boolean;today:string}){
 const [list,setList]=useState<List|null>(null),[newItem,setNewItem]=useState(""),[section,setSection]=useState(""),[draft,setDraft]=useState(false),[project,setProject]=useState(""),[reloadKey,setReloadKey]=useState(0),[projects,setProjects]=useState<{id:string;name:string}[]>([]);
 const {run,busy,error,setError}=useStructureActions();const flight=useRef<Promise<unknown>|null>(null);const card=useRef<HTMLDivElement>(null);
 const load=()=>api<List>("/quick-lists/"+id).then(setList);
 useEffect(()=>{void load().catch(e=>setError(e.message));void api<{items:{id:string;name:string}[]}>("/projects").then(d=>setProjects(d.items)).catch(()=>{});},[id]);
 useEffect(()=>{if(!busy&&!draft&&!newItem.trim()&&!error)void load().catch(e=>setError(e.message));},[id,refresh]);
 const action=(tool:string,args:unknown)=>{const promise=run<List>(tool,args).then(async result=>{if(tool==="quicklist.item")setList(result);else await load();setDraft(false);onChanged();});flight.current=promise;void promise.finally(()=>{flight.current=null;}).catch(()=>{});return promise;};
  const finish=async()=>{if(card.current?.contains(document.activeElement))(document.activeElement as HTMLElement)?.blur();if(flight.current)await flight.current;if(error)throw Error(error);if(newItem.trim())throw Error("Add or clear the unsaved checklist item before leaving.");};
 const close=()=>void finish().then(onClose).catch(e=>setError(e.message));
 useEditor({kind:"task",record_id:id,mode:"detail",auto_save:true,dirty:draft||!!newItem.trim(),busy:!list,schema:z.object({}),values:list?{title:list.title,items:list.items}: {},beforeLeave:finish,patch:async()=>{throw Error("Use Quick capture tools to edit this checklist.");},close:onClose});
 const editItem=(item:Task,patch:Record<string,unknown>)=>list&&action("quicklist.item",{list_id:id,expected_revision:list.revision,operation:"edit",item_id:item.id,expected_item_revision:item.revision,...patch}).catch(()=>{});
 const metadata=(patch:Record<string,unknown>)=>list&&action("task.update",{task_id:id,expected_revision:list.revision,...patch}).catch(()=>{});
 return <Dialog aria-label="Quick list" className="dialog-card capture-card" onEscape={close}><div ref={card}><button className="btn-icon capture-close" aria-label="Close Quick list" onClick={close}>×</button>{!list?<p>{error||"Loading list…"}</p>:<>
 <label className="field">List title<input aria-label="Quick list title" defaultValue={list.title} key={list.title+reloadKey} disabled={!canEdit||busy} onChange={()=>setDraft(true)} onBlur={e=>{if(e.target.value!==list.title)metadata({title:e.target.value});else setDraft(false);}}/></label><p role="status">{list.done} of {list.total} done · {list.total-list.done} remaining</p>
 {error&&<div role="alert"><p>{error} Unsaved text is kept.</p><button className="btn" onClick={()=>void load().then(()=>{setError("");setDraft(false);setNewItem("");setReloadKey(k=>k+1);})}>Reload saved list</button></div>}
 <div className="capture-options"><label className="field">Deadline<input aria-label="List deadline" type="date" disabled={!canEdit||busy} value={list.due_date??""} onChange={e=>metadata({due_date:e.target.value||null})}/></label><label className="field">Time<input aria-label="List deadline time" type="time" disabled={!canEdit||busy||!list.due_date} value={list.due_time?.slice(0,5)??""} onChange={e=>metadata({due_time:e.target.value||null})}/></label><label><input type="checkbox" disabled={!canEdit||busy} checked={list.planned_date===today} onChange={e=>metadata({planned_date:e.target.checked?today:null})}/> Pin to Today</label><label><input type="checkbox" disabled={!canEdit||busy||!list.due_date} checked={list.deadline_alert==="on"} onChange={e=>metadata({deadline_alert:e.target.checked?"on":"off"})}/> Deadline alert</label></div>
 <p className="footnote">Date-only alerts appear in the daily summary. Use task scheduling with Eri for a timed reminder.</p>
 <ol className="quick-checklist">{list.items.map((item,index)=><li key={item.id+":"+item.revision+":"+reloadKey}><input type="checkbox" aria-label={"Complete "+item.title} checked={item.status==="completed"} disabled={busy||!canEdit} onChange={e=>editItem(item,{completed:e.target.checked})}/><div className="quick-item-fields"><input aria-label={"Item "+(index+1)} defaultValue={item.title} disabled={busy||!canEdit} onChange={()=>setDraft(true)} onBlur={e=>{if(e.target.value!==item.title)editItem(item,{title:e.target.value});else setDraft(false);}}/><input aria-label={"Section for "+item.title} placeholder="Optional section" defaultValue={item.quick_section??""} disabled={busy||!canEdit} onChange={()=>setDraft(true)} onBlur={e=>{if(e.target.value!==item.quick_section)editItem(item,{section:e.target.value});else setDraft(false);}}/></div><div className="quick-order">{[-1,1].map(delta=><button key={delta} className="btn-icon" aria-label={(delta<0?"Move up ":"Move down ")+item.title} disabled={!canEdit||busy||index+delta<0||index+delta>=list.items.length} onClick={()=>{const order=list.items.map(t=>t.id);[order[index],order[index+delta]]=[order[index+delta],order[index]];void action("quicklist.item",{list_id:id,expected_revision:list.revision,operation:"reorder",order}).catch(()=>{});}}>{delta<0?"↑":"↓"}</button>)}</div></li>)}</ol>
 {canEdit&&<form className="quick-list-add" onSubmit={e=>{e.preventDefault();void action("quicklist.item",{list_id:id,expected_revision:list.revision,operation:"add",title:newItem,section}).then(()=>setNewItem("")).catch(()=>{});}}><input aria-label="New checklist item" placeholder="Add another item…" value={newItem} onChange={e=>setNewItem(e.target.value)}/><input aria-label="New item section" placeholder="Section (optional)" value={section} onChange={e=>setSection(e.target.value)}/><button className="btn" disabled={busy||!newItem.trim()}>Add</button></form>}
 {canEdit&&<details><summary>Use as normal tasks</summary><p>The same items become ordinary subtasks. Completion, IDs and history stay intact; nothing is copied.</p><select aria-label="Project for promoted list" value={project} onChange={e=>setProject(e.target.value)}><option value="">No project needed</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="btn" disabled={busy||draft||!!newItem.trim()} onClick={()=>void run("quicklist.promote",{list_id:id,expected_revision:list.revision,project_id:project||null}).then(()=>{onChanged();onClose();}).catch(()=>{})}>Promote to tasks</button></details>}
 </>}</div></Dialog>;
}
