import { Plus, X } from "lucide-react";
import type { Schema, SchemaField, SchemaType } from "./structure-types";
import { meanings, fieldKinds, describe, emptyField } from "./structure-types";

export function MultiSelect({label,values,options,onChange}:{label:string;values:string[];options:{id:string;name:string}[];onChange:(v:string[])=>void}){
  return <label>{label}<select multiple aria-label={label} value={values} onChange={e=>onChange(Array.from(e.target.selectedOptions,o=>o.value))}>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>;
}
export function TypeEditor({type,schema,original,update,mappings,onMappings}:{type:SchemaType;schema:Schema;original:Schema;update:(p:Partial<SchemaType>)=>void;mappings:Record<string,string>;onMappings:(m:Record<string,string>)=>void}){
  const field=(id:string,patch:Partial<SchemaField>)=>update({fields:type.fields.map(f=>f.id===id?{...f,...patch}:f)});
  const capability=(name:string,enabled:boolean)=>{
    const fields=type.fields.map(f=>({...f}));
    if(!enabled){for(const f of fields){const belongs=f.binding&&(name==="work"?["due_date","due_time","due_timezone","planned_date","priority","estimate_minutes","assignee"].includes(f.binding):name==="timeline"?["start_date","target_date"].includes(f.binding):name==="metric"&&f.binding.startsWith("metric_"));if(belongs){f.binding=null;f.archived=true;}}}
    if(enabled){const source=original.types.find(t=>t.id===(name==="work"?"task":name==="metric"?"goal":"project"));for(const f of source?.fields??[]){const match=f.binding&&(name==="work"?!f.binding.startsWith("metric_"):name==="metric"?f.binding.startsWith("metric_"):name==="timeline"&&["start_date","target_date"].includes(f.binding));if(match&&!fields.some(x=>x.binding===f.binding))fields.push(structuredClone(f));}}
    update({capabilities:enabled?[...type.capabilities,name]:type.capabilities.filter(c=>c!==name),fields,statuses:name==="work"&&enabled&&!type.statuses.length?meanings.map(s=>({id:s,name:describe(s),meaning:s})):type.statuses});
  };
  return <main><div className="schema-inline"><label>Singular name<input value={type.name} onChange={e=>update({name:e.target.value})}/></label><label>Plural name<input value={type.plural} onChange={e=>update({plural:e.target.value})}/></label></div>
    <label>Description <span className="required">Required</span><textarea required value={type.description} onChange={e=>update({description:e.target.value})} placeholder="What does this type mean? When should Eri use it?" rows={3}/></label>
    <fieldset><legend>Behaviors</legend>{[["work","Actionable work"],["content","Authored content"],["timeline","Timeline dates"],["metric","Outcome metric"]].map(([id,label])=><label className="check-label" key={id}><input type="checkbox" checked={type.capabilities.includes(id)} onChange={e=>capability(id,e.target.checked)}/>{label}</label>)}</fieldset>
    <MultiSelect label="Allowed main-home types" values={type.parent_types} options={schema.types.map(t=>({id:t.id,name:t.name}))} onChange={v=>update({parent_types:v})}/>
    <details open><summary>Fields <span>{type.fields.length}</span></summary>{type.fields.map(f=><fieldset key={f.id} className={f.archived?"archived-field":""}>
      <div className="schema-inline"><label>Field name<input value={f.name} onChange={e=>field(f.id,{name:e.target.value})}/></label><label>Value type<select value={f.kind} disabled={!!f.binding} onChange={e=>field(f.id,{kind:e.target.value})}>{fieldKinds.map(k=><option value={k} key={k}>{describe(k)}</option>)}</select></label></div>
      <label>Description <span className="required">Required</span><textarea rows={2} required value={f.description} onChange={e=>field(f.id,{description:e.target.value})}/></label>
      {f.kind==="relation"&&<><MultiSelect label="Links to types" values={f.target_types} options={schema.types.map(t=>({id:t.id,name:t.name}))} onChange={v=>field(f.id,{target_types:v})}/><label className="check-label"><input type="checkbox" checked={f.multiple} onChange={e=>field(f.id,{multiple:e.target.checked})}/>Allow multiple values</label></>}
      {["select","multiselect"].includes(f.kind)&&<div><span>Options</span>{f.options.map(o=><div className="schema-inline" key={o.id}><input aria-label="Option name" value={o.name} onChange={e=>field(f.id,{options:f.options.map(x=>x.id===o.id?{...x,name:e.target.value}:x)})}/><button aria-label={"Remove option "+o.name} onClick={()=>field(f.id,{options:f.options.filter(x=>x.id!==o.id)})}><X size={14}/></button></div>)}<button onClick={()=>field(f.id,{options:[...f.options,{id:crypto.randomUUID(),name:"New option"}]})}>Add option</button></div>}
      <button disabled={type.fields[0].id===f.id} onClick={()=>{const fields=[...type.fields];const i=fields.findIndex(x=>x.id===f.id);[fields[i-1],fields[i]]=[fields[i],fields[i-1]];update({fields});}}>Move field up</button>
      <div className="schema-inline"><label className="check-label"><input type="checkbox" checked={f.inherit} disabled={!!f.binding} onChange={e=>field(f.id,{inherit:e.target.checked})}/>Inherit through main home</label><label className="check-label"><input type="checkbox" checked={f.visible} onChange={e=>field(f.id,{visible:e.target.checked})}/>Visible</label><label className="check-label"><input type="checkbox" checked={f.archived} onChange={e=>field(f.id,{archived:e.target.checked})}/>Archived</label></div>
      {f.binding&&<small>Used by {describe(f.binding)} behavior.</small>}
    </fieldset>)}<button onClick={()=>update({fields:[...type.fields,emptyField()]})}><Plus size={15}/> Add field</button></details>
    <details><summary>Workflow statuses</summary>{type.statuses.map((s,index)=><div className="schema-inline" key={s.id}><label>Status name<input value={s.name} onChange={e=>update({statuses:type.statuses.map(x=>x.id===s.id?{...x,name:e.target.value}:x)})}/></label><label>Meaning<select value={s.meaning} onChange={e=>update({statuses:type.statuses.map(x=>x.id===s.id?{...x,meaning:e.target.value}:x)})}>{meanings.map(m=><option key={m} value={m}>{describe(m)}</option>)}</select></label><button aria-label={"Move "+s.name+" earlier"} disabled={!index} onClick={()=>{const statuses=[...type.statuses];[statuses[index-1],statuses[index]]=[statuses[index],statuses[index-1]];update({statuses});}}>↑</button><button aria-label={"Retire "+s.name} onClick={()=>update({statuses:type.statuses.filter(x=>x.id!==s.id)})}><X size={15}/></button></div>)}
      <button onClick={()=>update({statuses:[...type.statuses,{id:crypto.randomUUID(),name:"New status",meaning:"open"}]})}><Plus size={15}/> Add status</button>
      {original.types.find(t=>t.id===type.id)?.statuses.filter(s=>!type.statuses.some(x=>x.id===s.id)).map(s=><label key={s.id}>Move records from {s.name}<select value={mappings[s.id]??""} onChange={e=>onMappings({...mappings,[s.id]:e.target.value})}><option value="">Choose replacement…</option>{type.statuses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>)}
    </details><label className="check-label"><input type="checkbox" checked={type.archived} onChange={e=>update({archived:e.target.checked})}/>Archive this type</label>
  </main>;
}
